export const API = "https://api.thecatapi.com/v1";
export const CATS_LIST_FAIL = "CATS_LIST_FAIL";
export const CATS_LIST_LOADING = "CATS_LIST_LOADING";
export const CATS_LIST_SUCCESS = "CATS_LIST_SUCCESS";
export const CATS_CATEGORIES_FAIL = "CATS_CATEGORIES_FAIL";
export const CATS_CATEGORIES_LOADING = "CATS_CATEGORIES_LOADING";
export const CATS_CATEGORIES_SUCCESS = "CATS_CATEGORIES_SUCCESS";